Suggestions to simplify Session management
emhane/discv5 pull request #5
Opened 2024-01-15 08:01 UTC by AgeManning

I've made some changes which I think solve some bugs, simplify the code and make the diff smaller. 

The main part of it was moving unreachable enr tracking to inside the LRUTimeCache in a generic way, by adding the concept of tagging. Elements can be optionally tagged when inserted into the cache. If we need to know how many tagged elements are in there we can just go like `cache.tagged()`. 

This allows us to easily track the number of unreachable sessions, just by checking tagged. There are a number of reasons why I think this is an improvement:

- The code becomes much simpler and the diff from the original is smaller and I think we can remove a few dependencies
- The futures based channel approach was not doing what you were expecting I dont think. In the Nat Hole Puncher, we implemented a stream based on when elements would expire. I think we were expecting this stream to wake up when something expires, but the LRUTimeCache is not async so it doesn't wake up when an element got expired. Rather it would wake up when something got sent to that channel. That only happened when `get_mut()` or `len()` on the cache was called. So elements could expire (time-wise) but the task will not get awoken until either of these functions are called. More importantly, the channel does not get populated when `remove()` is called. So in the NATHolePuncher tracking case, these were not being registered. I replaced this logic with a HashSetDelay, because it seemed we only cared about when elements were expiring. This is a true async struct and will fire exactly when things expire. 
- When sessions were removed, via the `remove()` function, they were not being counted as being removed from the tracker.  I duplicated this logic in the nat_hole_puncher_tracker with a delay hashmap.
- Some sessions I think could be entered without being tracked also. From a WHOAREYOU. See here: https://github.com/emhane/discv5/blob/nat-hole-punch-discv5.2/src/handler/mod.rs#L870. So grouping the tracking logic into the cache helps isolate this logic and remove the chance of missing cases like this.

In addition a few more changes I made:
- I removed the `Clone` and `Copy` derive from Session and Keys. These are private keys and we don't want to copy them in memory for security reasons. For private keys, we try to keep one point in memory to store them and we zeroize that memory when it goes out of scope. I think the copy and clone were only needed for tests, from what I can tell. 
- I simplified the naming a bit

I think I have replicated all the logic however. If there's a mismatch let me know.

2024-01-15 21:16 UTC, emhane commented on src/handler/mod.rs
> +                && Some(self.sessions.tagged()) > self.nat_utils.unreachable_enr_limit
```suggestion
                && Some(self.sessions.tagged() + 1) > self.nat_utils.unreachable_enr_limit
```

2024-01-15 21:17 UTC, emhane commented on src/handler/mod.rs
> +            // Decide whether to establish this connection based on our apettiite for unreachable
```suggestion
            // Decide whether to establish this connection based on our appetite for unreachable
```

2024-01-15 21:30 UTC, emhane commented on src/config.rs
> +    /// NAT. Default is no limit. Minimum is 10.
nice, that crosses off the second todo I still had open https://github.com/sigp/discv5/pull/176#issuecomment-1877505234

2024-01-15 21:39 UTC, emhane requested changes
lgtm, not so good to clippy. left a some suggestions, if you commit those I'm happy with it.

2024-01-15 22:31 UTC, jxs commented on src/handler/nat_hole_punch/utils.rs
>          listen_sockets: impl Iterator<Item = &'a SocketAddr>,
nit: [`SocketAddr` is `Copy`](https://doc.rust-lang.org/std/net/enum.SocketAddr.html#impl-Copy-for-SocketAddr) we can remove the lifetimes and have `listen_sockets: &[SocketAddr]` [see here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fdf38a7b58aa9b867785d18f6f306bf3)

2024-01-15 22:31 UTC, jxs commented on src/handler/nat_hole_punch/utils.rs
> +        enr.udp4_socket().is_some() || enr.udp6_socket().is_some()
nit:
```suggestion
        enr.udp4_socket().or(enr.udp6_socket()).is_some()
```

2024-01-15 22:31 UTC, jxs commented on src/lru_time_cache.rs
> +    #[allow(dead_code)]
```suggestion
```
if this is `pub` we should not need the `#[allow(dead_code)]`

2024-01-15 22:31 UTC, jxs commented on src/lru_time_cache.rs
>      #[allow(dead_code)]
```suggestion
```
same as above

2024-01-17 04:01 UTC, AgeManning commented on src/handler/mod.rs
> +                && Some(self.sessions.tagged()) > self.nat_utils.unreachable_enr_limit
Can this just be `>=` ?

2024-01-17 04:07 UTC, AgeManning commented on src/handler/nat_hole_punch/utils.rs
> +        enr.udp4_socket().is_some() || enr.udp6_socket().is_some()
Dont think we can do this, because the types are different. SocketAddrv4 vs SocketAddrv6

2024-01-17 04:09 UTC, AgeManning commented on src/lru_time_cache.rs
> +    #[allow(dead_code)]
Yeah. The idea was to use this as an external crate. Not sure if we ended up doing it or not yet. 

These functions were for being generic in an external crate. We could remove them, but wasn't sure if we were using them later or not.

2024-01-17 04:09 UTC, AgeManning commented on src/lru_time_cache.rs
> +    #[allow(dead_code)]
I think i'll just delete them for now

2024-01-17 04:12 UTC, AgeManning commented
Ok. I think i've addressed everything here. Will continue with the main review :)

2024-01-17 14:44 UTC, merged